channels:
    - pytorch
    - conda-forge
name:
    sam
dependencies:
    - cpuonly
    - napari
    - pooch
    - python-elf >=0.4.8
    - pytorch
    - segment-anything
    - torchvision
    - torch_em >=0.5.1
    - tqdm
    # - pip:
    #     - git+https://github.com/facebookresearch/segment-anything.git
