channels:
    - pytorch
    - conda-forge
name:
    sam
dependencies:
    - cpuonly
    - napari
    - pip
    - pooch
    - python-elf >=0.4.8
    - pytorch
    - segment-anything
    - torchvision
    - torch_em >=0.5.1
    - tqdm
    - timm
    - pip:
        - git+https://github.com/ChaoningZhang/MobileSAM.git
    #   - git+https://github.com/facebookresearch/segment-anything.git
